version: '3'

services:
  webreg-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - webreg-db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://webreg_db:5432/webRegistration
    networks:
      - webreg-net

  webreg-db:
    image: postgres:14
    container_name: webreg_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webRegistration
    ports:
      - "5432:5432"
    volumes:
      - db-webreg:/var/lib/postgresql/data
    restart: always
    networks:
      - webreg-net

volumes:
  db-webreg:

networks:
  webreg-net:
    driver: bridge